Make documentation HTML renderable
negrutiu/nsis-nscurl pull request #10
Opened 2023-11-13 01:04 UTC by Nadahar

Hi.

Thanks for making this great plugin. I just made this little PR as a "suggestion" as it makes the documentation easier to read from GitHub.

2023-11-17 06:48 UTC, negrutiu requested changes
Great suggestion, thank you.
How about changing the link to point to the latest file version (instead of a specific commit)?

2023-11-17 06:48 UTC, negrutiu commented on README.md
> +- A lot more... Check out the included [documentation](https://rawcdn.githack.com/negrutiu/nsis-nscurl/6c9f7c02b050f5db62963d6a9962d6b791e4c7a4/NScurl.Readme.htm)
```suggestion
- A lot more... Check out the included [documentation](https://raw.githack.com/negrutiu/nsis-nscurl/master/NScurl.Readme.htm)
```

2023-11-17 06:48 UTC, negrutiu commented on README.md
> +- More complex examples in the [documentation](https://rawcdn.githack.com/negrutiu/nsis-nscurl/6c9f7c02b050f5db62963d6a9962d6b791e4c7a4/NScurl.Readme.htm)
```suggestion
- More complex examples in the [documentation](https://raw.githack.com/negrutiu/nsis-nscurl/master/NScurl.Readme.htm)
```

2023-11-17 17:48 UTC, Nadahar commented
The reason I didn't point to the branch/master/main is what they say here: http://raw.githack.com/

I don't fully understand what they do, but they somehow cache the result so that it won't be dynamically updated. That said, they do say that you can link to a branch "for development", but that they will throttle traffic for these. "For development" and "in production" isn't defined any further, so it's kind of hard to know what to consider this. I doubt this will cause any significant traffic. I'd say that choice should be up to you 😉

2023-11-18 07:30 UTC, negrutiu approved these changes

2023-11-18 07:30 UTC, merged